

import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div>

      <title>Chat App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <Sidebar />
    </div>
  )
}
